import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Inter } from 'next/font/google';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import GlobalLayout from "@/layout/GlobalLayout";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'], 
  display: 'swap',     
  variable: '--font-roboto',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`font-sans ${inter.variable}`}>
      <body
        className={`${roboto.variable} antialiased max-w-400 m-auto`}
      >
        <StoreProvider>
          <GlobalLayout>
            {children}
          </GlobalLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
