drop table if exists public.news cascade;

drop policy if exists "Allow authenticated uploads 1tnhfnw_0" on storage.objects;
drop policy if exists "Allow authenticated uploads 1tnhfnw_1" on storage.objects;
drop policy if exists "Allow authenticated uploads 1tnhfnw_2" on storage.objects;
drop policy if exists "Allow authenticated uploads 1tnhfnw_3" on storage.objects;
drop policy if exists "Allow authenticated uploads bnbwlr_0" on storage.objects;
drop policy if exists "Allow authenticated uploads bnbwlr_1" on storage.objects;
drop policy if exists "Movies images are viewable by everyone" on storage.objects;
drop policy if exists "News images are viewable by everyone" on storage.objects;
drop policy if exists "Brands logos are viewable by everyone" on storage.objects;
drop policy if exists "Only super_admin can upload movie images" on storage.objects;
drop policy if exists "Only super_admin can update movie images" on storage.objects;
drop policy if exists "Only super_admin can delete movie images" on storage.objects;
drop policy if exists "Only super_admin can upload news images" on storage.objects;
drop policy if exists "Only super_admin can update news images" on storage.objects;
drop policy if exists "Only super_admin can delete news images" on storage.objects;
drop policy if exists "Only super_admin can upload brand logos" on storage.objects;
drop policy if exists "Only super_admin can update brand logos" on storage.objects;
drop policy if exists "Only super_admin can delete brand logos" on storage.objects;
drop policy if exists "Super admin can view all profiles" on public.profile;
drop policy if exists "Users can view own profile" on public.profile;
drop policy if exists "Users can insert own profile" on public.profile;
drop policy if exists "Users can update own profile" on public.profile;
drop policy if exists "Movies are viewable by everyone" on public.movies;
drop policy if exists "News are viewable by everyone" on public.news;
drop policy if exists "Theaters are viewable by everyone" on public.theater;
drop policy if exists "Screens are viewable by everyone" on public.screen;
drop policy if exists "Seats are viewable by everyone" on public.seats;
drop policy if exists "Showtimes are viewable by everyone" on public.showtimes;
drop policy if exists "Cities are viewable by everyone" on public.cities;
drop policy if exists "Brands are viewable by everyone" on public.brands;
drop policy if exists "Active discounts are viewable by everyone" on public.discount;
drop policy if exists "Users can view own locked seats" on public.seat_locked;
drop policy if exists "Users can insert own locked seats" on public.seat_locked;
drop policy if exists "Users can update own locked seats" on public.seat_locked;
drop policy if exists "Users can view own bookings" on public.bookings;
drop policy if exists "Users can insert own bookings" on public.bookings;
drop policy if exists "Users can update own bookings" on public.bookings;
drop policy if exists "Users can view own booking seats" on public.booking_seats;
drop policy if exists "Users can insert own booking seats" on public.booking_seats;
drop policy if exists "Users can view own payments" on public.payments;
drop policy if exists "Users can insert own payments" on public.payments;
drop policy if exists "Users can update own payments" on public.payments;
drop function if exists public.get_current_user_role cascade;